name: Compilation & Code Analysis
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter 
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.2.3'
          
      - name: Install flutter dependencies
        run: flutter pub get
      - name: Format files
        run: flutter format lib/
      - name: Analyze code
        run: flutter analyze
      - name: Run test suite
        run: flutter test
